name: Build and generate doc

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: |
            docbuild/.lake/packages
            docbuild/.lake/build
          key: ${{ runner.os }}-lean-${{ hashFiles('**/lake-manifest.json') }}
      
      - uses: leanprover/lean-action@v1
        with:
          use-mathlib-cache: "false"
          check-reservoir-eligibility: "false"
        
      - name: Build docs
        run: |
          cd docbuild
          lake update doc-gen4
          lake build AutoKchp:docs
      
      - name: Prepare pages
        run: |
          mkdir -p site
          cp -r docbuild/.lake/build/doc site/docs
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
